spring:
  application:
    name: eureka-hystrix
server:
  port: 8084


debug: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka

eureka-hystrix:
  ribbon:
    listOfServers: localhost:8081 #,localhost:8082  #配置Ribbon能访问 的微服务节点，多个节点用逗号隔开
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule; #配置Ribbon负载均衡策略
