
spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        git:
          uri:  #git仓库位置
          search-paths: #git仓库下搜索位置
          username: # git仓库访问名
          password: # git仓库访问密码

server:
  port: 8087


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka

