
spring:
  application:
    name: eureka-zuul
server:
  port: 8086


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  ignored-services: eureka-client #忽略服务
  routes:
    eureka-zuul:
      serviceId: eureka-zuul
      path: /**
#    eureka-client:
#        path: /**
#        serviceId:  eureka-client
#        stripPrefix: true

