spring:
  application:
    name: eureka-config-client
  cloud:
    config:
      profile: dev  #环境
      label: master #git分支
      uri:  http://127.0.0.0:8087  #eureka-config-server 地址

server:
  port: 8088


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka
