
spring:
  application:
    name: eureka-client
server:
  port: 8081


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8080/eureka